### ISSUE TITLE
Great plugin, thanks - needs a bit more documentation

### ISSUE THREAD

**Issue by stutteringp0et** [fxa90id/certbot-dns-stackpath#1]
If you're looking at this plugin, not knowing how to set it up - it's not difficult, it just isn't documented.

You'll need to create a credentials document with 3 details.

After you set up API credentials in  your StackPath account - you'll need the client id and secret.

You'll also need a 3rd item the "stack id", which isn't really well identified in the StackPath account page.

You'll find it labeled as the "SLUG" on your "My Stacks" account page.  The one for my account looks like "my-default-stack-abc123"

When you create your credentials.ini file, it needs 3 items:

dns_stackpath_client_secret = xyz
dns_stackpath_client_id = xyz
dns_stackpath_stack_id = my-default-stack-abc123

**Comment by stutteringp0et** [comment]
I just wanted to add a bit if info that I think will help the next guy.

**Comment by fxa90id** [comment]
Thanks :)
